[package]
name = "hudsucker"
version = "0.4.2"
edition = "2018"
description = "MITM HTTP/S proxy"
documentation = "https://docs.rs/hudsucker"
readme = "README.md"
homepage = "https://github.com/omjadas/hudsucker"
repository = "https://github.com/omjadas/hudsucker"
license = "MIT"
keywords = ["http", "proxy"]
categories = ["network-programming"]
exclude = [".github/"]

[dependencies]
async-compression = { version = "0.3", features = ["tokio", "brotli", "gzip", "zlib"] }
async-trait = "0.1"
bytes = "1"
chrono = "0.4"
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
hyper-proxy = { version = "0.9", default-features = false, features = ["rustls-webpki"] }
hyper-rustls = { version = "0.22", features = ["webpki-tokio"] }
hyper-tungstenite = "0.4"
log = "0.4"
moka = { version = "0.5", features = ["future"] }
rcgen = { version = "0.8", features = ["x509-parser"] }
rustls = "0.19"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.22"
tokio-tungstenite = { version = "0.15", features = ["rustls-tls"] }
tokio-util = { version = "0.6", features = ["io"] }

[dev-dependencies]
env_logger = "0.9"
